name: Continuous Deployment
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make all
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: yves.chevallier@heig-vd.ch
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: _build/html

